name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        subdir: [ sub1, sub2 ]

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Unit Test
          run: ./gradlew testDebugUnitTest
          - name: Android Test Report
            uses: asadmansr/android-test-report-action@v1.2.0
            if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: app/build/reports/
      - name: Upload APK
          uses: actions/upload-artifact@v3
          with:
            name: build-APK
            path: app/build/outputs/apk/