name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: currency.jks created
        run: |
            echo "${{ secrets.RELEASE_KEYSTORE }}" > currency.jks.asc
            gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch currency.jks.asc > /home/runner/work/CurrencyApp/CurrencyApp/app/currency.jks
      - name: Build with Gradle
        run: ./gradlew build
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: build-APK
          path: app/build/outputs/apk/
      - name: Create AAB
        run: ./gradlew bundleRelease
      - name: account.json created
        run: |
            echo "${{ secrets.ACCOUNT }}" > account.json.asc
            gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch account.json.asc > /home/runner/work/CurrencyApp/CurrencyApp/app/account.json
      - name: Upload APK to Google Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ACCOUNT_JSON }}
          packageName: com.androidbestapplication.currencyapp
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew